### ISSUE TITLE
Resizeable Members List causes members list to reverse every so often?

### ISSUE THREAD

**Issue by Kliuqard** [programmer2514/BetterDiscord-CollapsibleUI#123] opened 2024-02-19 17:25 UTC
![Backwards Member list](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/160526886/b33e0086-1020-4355-ad4b-ee709a9692ab)

I apologize if this is not the most descriptive, but the members list will flash and appear reversed after swapping to certain channels. The cause seems to be related to the messages in the channel I'm swapping to, but I can't seem to confidently narrow specifically what content is triggering this. Perhaps images?

Weirdly enough, it fixes itself on the same tab if I enter it through exiting the settings page.

**Comment by programmer2514** [comment] 2024-02-20 22:43
This is actually a duplicate of #92 - I am aware of it but cannot reproduce the behavior on my device, and thus am having a lot of trouble trying to fix it.

**Closed by programmer2514** 2024-02-20 22:43 UTC
