### ISSUE TITLE
Channel list uncollapses unexpectedly

### ISSUE THREAD

**Issue by CrimsonCuttle** [programmer2514/BetterDiscord-CollapsibleUI#71] opened 2023-01-25 00:32 UTC
When I press shift, the channel list uncollapses, despite there being no mention of the shift key anywhere in the plugin's settings. It will also sometimes just uncollapse by itself randomly, regardless of mouse position.

**Comment by programmer2514** [comment] 2023-01-26 15:31
That is quite odd. I can't seem to reproduce it though. Could you try a few troubleshooting steps for me?
1) Disable all your other plugins and see if that fixes it. If it does, re-enable them one at a time until it breaks again, and then tell me the plugin that broke it.
2) Send me the contents of your `CollapsibleUI.config.json` settings file (it should just be in your BetterDiscord plugins folder with the plugin itself).
3) The next time you notice it happen, open the developer tools (Ctrl+Shift+I), go to the console tab, look for any errors (highlighted red) or warnings (highlighted yellow), and then send me screenshots of any that start with a blue `[CollapsibleUI]`.

**Comment by CrimsonCuttle** [comment] 2023-02-04 04:32
Hmm, it seems to be the 'PersonalPins' plugin that does it, actually. 
Although, after it reproducing a few times, it suddenly went away. Next time it happens though, if it does, I will update with the recent console log.

**Comment by R3D-C0M3T** [comment] 2023-02-04 05:38
I've been having the same issue for a couple months now, every time I press shift. I was also unable to reliably pin down a conflicting plugin (and I can't seem to get my developer tools to show up), but here is a copy of the config file.
[CollapsibleUI.config.txt](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/files/10607763/CollapsibleUI.config.txt)

**Comment by R3D-C0M3T** [comment] 2023-02-09 23:16
I'd like to add that this also happens consistently when scrolling up in any channel, every time it loads more messages it uncollapses.

**Comment by programmer2514** [comment] 2023-02-15 01:43
Alright, update (sorry it took so long, I've been trying to find time between balancing uni classes).
It seems to be caused by resizing the channel list to a custom width and then triggering a UI reload.
I should be able to push a fix for it soon. Thanks for the report!

**Comment by programmer2514** [comment] 2023-02-15 02:56
Alright, this should be fixed in v7.0.4 :)

**Closed by programmer2514** 2023-02-15 02:56 UTC
Labels: bug
