### ISSUE TITLE
Any additional message bar buttons get cut off

### ISSUE THREAD

**Issue by afgks** [programmer2514/BetterDiscord-CollapsibleUI#130] opened 2024-05-11 08:17 UTC
I often rely on the gif, sticker, emoji buttons in the message bar, but at the moment, when the plugin is enabled, there is no way to unhide the buttons.

Also a bug. When the "Show send message button" option is enabled in Settings > Accessibility, the send button appears cut off.
<img width="436" alt="sshot-2024-05-11- 09-13-10" src="https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/11691936/38d23bab-9c91-44da-bcda-6fe313df56d6">

When the InvisibleTyping plugin is installed, the send button doesn't even appear at all.
<img width="440" alt="sshot-2024-05-11- 06-50-57" src="https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/11691936/b45ced00-4cd6-4bee-8575-14403668ba80">

**Comment by programmer2514** [comment] 2024-05-19 04:16
Apologies for the delay in my response - I had to focus on my finals.

The GIF, sticker, and emoji buttons in the message bar should expand out if you hover over the emojis button, but if you would prefer they are always shown, there actually is a setting for that! You should be able to go to CollapsibleUI's settings page and toggle on `Disable Message Bar Button Auto-collapse` under the `Main` category, after which all the buttons should be visible.

As for the send message button being cut off, I cannot seem to reproduce this behavior, with or without InvisibleTyping. Does this issue persist if CollapsibleUI is the only plugin/theme you have enabled? If so, what version of Discord are you using (Stable, Beta, Canary) and have you modified any CollapsibleUI settings?

If the issue is related to CollapsibleUI, you may also be able to fix it by deleting the file `CollapsibleUI.config.json` (located in your plugins folder next to the `CollapsibleUI.plugin.js` file) and restarting Discord. Be aware that this will reset any changes you have made in CollapsibleUI's settings page.

**Comment by programmer2514** [comment] 2024-05-22 02:09
Thank you for the additional information - I can confirm that the issue with the send message button was introduced in PTB but is not yet present in Stable. I am working on a fix and should hopefully have it released within the next 24 hours :)

**Closed** 2024-05-22 02:31 UTC
Labels: bug, ptb
