### ISSUE TITLE
resizing and member list issues

### ISSUE THREAD

**Issue by SaltyStarfruit** [programmer2514/BetterDiscord-CollapsibleUI#119] opened 2024-02-10 02:30 UTC
The main usecase I have for this plugin is to collapse the member list so all i see are the server member's icons. This was working just fine until a few days ago, when the entire plugin seemed to stop working. The member list has stayed collapsed to where I last set it, however, all i see is the end of people's names. In addition, I cannot seem to get the plugin to allow me to resize UI elements at all anymore, as when I try the option to click the left corner and resize the element does not even come up. 
attatched is a picture of what my member list looks like in a server. I have tried playing with the settings, reinstalling the plugin after deleting both it and it's associated config file, all to no avail. Really really enjoy this plugin, as I keep discord on my vertical monitor, so this has become an indespensible resource for making discord work properly on there; hope theres a proper solution :D
![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/159598928/49c171ee-18ff-4d25-a314-2731b45f66e3)

**Comment by programmer2514** [comment] 2024-02-10 02:34
Duplicate of #116

**Closed** 2024-02-10 02:34 UTC
Labels: bug, duplicate
