### ISSUE TITLE
Channel list doesn't collapse properly

### ISSUE THREAD

**Issue by JELLYKITTEN7** [programmer2514/BetterDiscord-CollapsibleUI#150] opened 2024-12-18 19:44 UTC
The plugin worked fine for a few weeks, then suddenly this glitch appeared. As far as I know, I haven't done anything weird to cause it.

The channel list acts as though it collapses, yet it still remains visible overtop of the messages tab. This happens both with and without the theme. I've tried repairing BetterDiscord, deleting and reinstalling the plugin, updating everything I could... Nothing has worked so far.

https://github.com/user-attachments/assets/7a57948a-1484-44df-84f8-76c8eb528d85

**Comment by programmer2514** [comment] 2024-12-18 22:07
Duplicate of #149 ‐ This is caused by Discord updating their classes. A fix should be available sometime next week. Sorry for the inconvenience.

**Closed** 2024-12-18 22:07 UTC
Labels: bug, duplicate
