### ISSUE TITLE
Collaspible UI buttons do nothing on servers

### ISSUE THREAD

**Issue by DontBotherYT** [programmer2514/BetterDiscord-CollapsibleUI#118] opened 2024-02-09 15:07 UTC
I have the UI menu open on servers, but when I press the button to collapse or un-collapse certain elements, it won't perform the requested actions. I prefer to keep the member list in servers off while having the channel list visible for navigation. But Auto-uncollapse won't work unless I'm in DMs. I click on the Member List option to collapse it and nothing happens. Everything worked back in November, but suddenly stopped working mid-January.

**Comment by programmer2514** [comment] 2024-02-10 02:32
Duplicate of #116

**Closed** 2024-02-10 02:33 UTC
Labels: bug, duplicate
