### ISSUE TITLE
Can't type ` in the message bar.

### ISSUE THREAD

**Issue by Jugom** [programmer2514/BetterDiscord-CollapsibleUI#54] opened 2022-10-26 15:43 UTC
Just like that.
If I try to send a message that contains the ``  symbol (like for formatting), it won't let me.  Curiously enough, I have no trouble typing in in the search bar for example (or anywhere else outside of discord).
I checked every other key in my keyboard and they all work fine. only ` has problems. if it's worth anything I need to Shift + ´  to get  ``` .
If I press it repeatedly (like a lot) or leave the key pressed for a while, it will sometimes input a couple.

and ofc, if I disable Collapsible UI, I can type it with no inconveniences.

**Comment by programmer2514** [comment] 2022-10-28 00:21
Duplicate of #52

**Closed** 2022-10-28 00:21 UTC
