### ISSUE TITLE
Friendlist opens even if cursor isn't that close

### ISSUE THREAD

**Issue by Zzeyy** [programmer2514/BetterDiscord-CollapsibleUI#70] opened 2023-01-20 12:21 UTC
https://user-images.githubusercontent.com/97387354/213693700-aa2fb05d-5038-45dc-9a96-e2fc85b9a748.mp4

**Comment by Zzeyy** [comment] 2023-01-20 12:21
Just to clarify, there's a blur in the video.

**Comment by Zzeyy** [comment] 2023-01-20 12:22
This issue makes working with servers slightly irritating.

**Comment by programmer2514** [comment] 2023-01-21 23:09
This is not a bug, it's just the default.
It can easily be changed in the plugin settings under `Dynamic Uncollapse > Channel List Opening/Closing Distance`

**Closed by programmer2514** 2023-01-21 23:09 UTC

**Comment by Zzeyy** [comment] 2023-01-23 01:45
Even if it is default and can be changed, it's just way too far.
