### ISSUE TITLE
collapsable ui not working on servers anymore

### ISSUE THREAD

**Issue by Masono03** [programmer2514/BetterDiscord-CollapsibleUI#11] opened 2022-01-05 23:46 UTC
as the title says on newest canary collapsible ui only work on dms now and discord goes back to normal looking as soon as u click a server

**Comment by programmer2514** [comment] 2022-01-10 16:31
Could you please, when this happens, press Ctrl+Shift+I, find the red error message, and send me a screenshot of it?
Thanks!

**Comment by Masono03** [comment] 2022-01-11 11:02
now it doesnt work at all anymore this is what it says:

624b5501fd5b5bef4f3b.js:130 [PluginManager] Unable to fire onSwitch for CollapsibleUI v2.1.1 TypeError: Cannot read property 'style' of null
    at CollapsibleUI.initialize (betterdiscord://plugins/CollapsibleUI.plugin.js:117)
    at CollapsibleUI.onSwitch (betterdiscord://plugins/CollapsibleUI.plugin.js:342)
    at Object.onSwitch (<anonymous>:4:310393)
    at Object.dispatch (<anonymous>:4:227726)
    at EventEmitter.<anonymous> (<anonymous>:4:237305)

**Comment by programmer2514** [comment] 2022-01-11 11:32
This was caused by the latest Discord update. I am working on a fix right now and will have it released in a couple days :)

**Closed** 2022-01-11 13:27 UTC
Labels: bug
