### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ashergz** [programmer2514/BetterDiscord-CollapsibleUI#25] opened 2022-05-05 17:13 UTC
As can be seen, the collapse UI sliding menu no longer displayes in the toolbar when the plugin is enabled.

![image](https://user-images.githubusercontent.com/35883201/166976626-5d6a2ea1-ff36-4889-961a-fc39143e6fae.png)

Moreover, the plugin settings page is not opening either.

![image](https://user-images.githubusercontent.com/35883201/166976847-6e1509e6-03a8-4f33-95b8-e820e7b1cdec.png)

Please look into this. Thanks.

**Comment by programmer2514** [comment] 2022-05-05 19:09
What version of Discord are you using? I cannot reproduce this in the latest Stable release

**Comment by Masono03** [comment] 2022-05-07 00:29
Broken for me too: 

Canary 127283 (ad912ed)
BetterDiscord 1.5.3
Host 1.0.46 Windows 10 64-Bit (10.0.19044

**Comment by ashergz** [comment] 2022-05-07 06:15
> What version of Discord are you using? I cannot reproduce this in the latest Stable release

So

**Comment by ashergz** [comment] 2022-05-07 06:26
Did not mean to closse the issue. Sorry about that.

I'm on stable discord. Let me give you a little background on how the issue started for me.

One day I started discord and was greeted with the changelog popup for CollapsibleUI 4.4.2. I closed it and discovered that the plugin wasn't working. So I tried to disable and reenable it but no show. Tried opening the plugin settings and got the error above. Tried restarting discord, changelog popup showed again (and keeps showing every time I open discord) and plugin still doesn't work.

In the end, I was able to fix the issue by deleting the plugin from the plugin folder along with its config file, and then redownloading from git. However, today when I started discord, the changelog popup again showed up and startup and rinse repeat.

Hope that helps.

**Comment by programmer2514** [comment] 2022-05-07 15:42
I still cannot seem to reproduce this. The next time it happens, could you open developer tools and send me any errors/warnings in the console logs? (BetterDiscord > Settings > Developer Settings > DevTools, then reload and press Ctrl+Shift+i)

**Comment by Masono03** [comment] 2022-05-08 01:08
cant find aynthing in my logs but i fiddled around with settings turning some auto collapse and such off and suddendly everything is back to normal? did a update turn a auto collapse on default  on accident maybe?

**Comment by programmer2514** [comment] 2022-05-08 01:39
Nah, I haven't made any changes to persistent settings at all. The only thing I can think of is a mistake I made with a version number mismatch that could've messed with ZeresPluginLibrary. If that is what caused, it should be fixed now but I'm going to leave this open until I get full confirmation

**Comment by ashergz** [comment] 2022-05-08 07:33
Can confirm. Latest update fixes the issue. Thanks a lot!

**Closed** 2022-05-08 14:07 UTC
Labels: bug
