### ISSUE TITLE
Member list uncollapse when changing to threads

### ISSUE THREAD

**Issue by OnyxL** [programmer2514/BetterDiscord-CollapsibleUI#142] opened 2024-11-04 22:48 UTC
**Describe the bug**
Member list uncollapse when changing to threads or changing server

**Expected behavior**
Maybe this isnt a bug but I would like an option to keep the member list closed when changing threads or server

**Comment by programmer2514** [comment] 2024-11-06 16:49
This is a bug - thanks for the report!

**Comment by programmer2514** [comment] 2024-11-10 04:03
This should be fixed in v8.5.0

**Closed by programmer2514** 2024-11-10 04:03 UTC
Labels: bug, stable

**Comment by OnyxL** [comment] 2024-11-10 05:40
I still got the same bug after updating, the member list pops back out when switching to channels/threads that got different member lists

**Comment by programmer2514** [comment] 2024-11-10 05:52
I cannot reproduce this behavior on the latest published version.

Does this issue persist if all other plugins/themes are disabled? 
What are the contents of your config file (`%AppData%\betterdiscord\plugins\CollapsibleUI.config.json`)?

**Comment by OnyxL** [comment] 2024-11-10 05:55
yes

{
    "currentVersionInfo": {
        "version": "8.5.0",
        "hasShownChangelog": true
    },
    "cuiSettingsVersion": "13",
    "disableTransitions": "true",
    "transitionSpeed": "250",
    "disableToolbarCollapse": "true",
    "disableSettingsCollapse": "true",
    "enableFullToolbarCollapse": "false",
    "dynamicUncollapse": "false",
    "dynamicUncollapseDelay": "0",
    "resizableChannelList": "false",
    "channelListWidth": "229",
    "disabledButtonsStayCollapsed": "false",
    "settingsButtonsMaxWidth": "100",
    "toolbarIconMaxWidth": "300",
    "toolbarMaxWidth": "800",
    "userAreaMaxHeight": "300",
    "msgBarMaxHeight": "400",
    "windowBarHeight": "18",
    "collapsedDistance": "0",
    "autoCollapse": "true",
    "keyBindsEnabled": "true",
    "serverListButtonActive": "true",
    "channelListButtonActive": "true",
    "msgBarButtonActive": "true",
    "windowBarButtonActive": "true",
    "membersListButtonActive": "true",
    "userAreaButtonActive": "true",
    "callContainerButtonActive": "true",
    "conditionalAutoCollapse": "false",
    "dynamicUncollapseDistance": "0,0,0,0,0,0,0,0",
    "dynamicUncollapseCloseDistance": "0,0,0,0,0,0,0,0",
    "autoCollapseThreshold": "500,600,400,200,950,400,550,1000",
    "autoCollapseConditionals": ",,,,,,,",
    "buttonsOrder": "1,2,0,6,0,3,5,8",
    "dynamicUncollapseEnabled": "false,false,false,false,false,false,false,false",
    "keyStringList": "Alt+S,Alt+C,Alt+T,Alt+W,Alt+Z,Alt+U,Alt+P,Alt+I",
    "disableMsgBarBtnCollapse": "false",
    "messageBarButtonsMinWidth": "40",
    "buttonCollapseFudgeFactor": "10",
    "resizableMembersList": "true",
    "floatingDynamicUncollapse": "true",
    "resizableUserProfile": "true",
    "membersListWidth": "0",
    "profilePanelWidth": "0",
    "persistentUnreadBadge": "false",
    "profilePanelButtonActive": "false",
    "messageBarButtonsMaxWidth": "300"
}

**Comment by programmer2514** [comment] 2024-11-10 06:10
> "membersListButtonActive": "true",

> "disabledButtonsStayCollapsed": "false",

> "buttonsOrder": "1,2,0,6,0,3,5,8",
> Members list -----------^

This config shouldn't collapse the members list at all.

**Comment by OnyxL** [comment] 2024-11-10 06:12
Oh, I was only using the shortcut until now. Its working now, ty.

**Comment by programmer2514** [comment] 2024-11-10 06:15
No problem, glad I could help!
