### ISSUE TITLE
Plugin's buttons sometimes get replaced by the default Discord Members List button

### ISSUE THREAD

**Issue by Aluerie** [programmer2514/BetterDiscord-CollapsibleUI#85] opened 2023-03-29 16:11 UTC
I don't know exact reproduction steps but here is the video (my mouse highlighter was set to have a huge delay+fade, so vid looks a bit laggy, sorry). 

Sometimes when switching between channels you get a screen where the default Member list is shown as clicked on, but in reality the member list is off so

* you click on "Hide Member List" (but the list is already hidden) -> the button becomes off (default "Show Member List")
* you click on "Show Member List" -> the list does not come but the extension buttons appear
* you click on extension's "Members List (Alt+M) -> the list appears.

https://user-images.githubusercontent.com/33165440/228600786-052c88ab-ac90-4140-842e-667d8316e774.mp4

Note that from the starting position keybinds like Alt+S Alt+M still work fine (but they don't fix wrong+missing icons).

And I'm sorry, I'm not sure what exactly triggers such position. Looks like switching between channels where you had member list off does that.

**Comment by programmer2514** [comment] 2023-03-29 19:22
This is caused by an external UI update from another plugin (most likely BDFDB) not being handled correctly by my plugin.
It is a bug, but in order to fix it I need steps by which I can reproduce it.

**Comment by Aluerie** [comment] 2023-03-29 20:17
this issue is still there with plugins switches set like this, emptied Custom CSS and BetterDiscord version 1.9.1: 

![bug-showcase](https://user-images.githubusercontent.com/33165440/228653709-0acbbff7-7e7e-423c-9ea1-8a639aae5e58.png)

my config file is this: https://mystb.in/PastorShowedOmega

Okay so with setup from above:
* I restarted discord 
* I clicked my private server 
* started the following recording:

https://user-images.githubusercontent.com/33165440/228656353-9827741e-c8fa-4c23-9b05-856d5bbc3261.mp4

**Comment by programmer2514** [comment] 2023-04-26 02:07
This should be fixed in the latest release - let me know if it still happens

**Closed** 2023-04-26 02:07 UTC
Labels: bug
