### ISSUE TITLE
Does not allow menu access within a group chat.

### ISSUE THREAD

**Issue by foxsouns** [programmer2514/BetterDiscord-CollapsibleUI#117] opened 2024-02-07 08:57 UTC
the collapsible menu does not appear while in a group chat. the default collapse profile behavior is also non-functional while in a group chat, and there is no hover text for the button. tested and works in single member chats, and in servers. not familiar with the source code for this, but a presumed fix for this would be to either change the "show/hide members" button into a "show/hide user profile" button, or ensure behaviors get applied to both buttons.

example:
![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/60267141/546a913b-cbd6-43a0-ae3e-343d52a1eca6)

expected result:
![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/60267141/f675d8cd-163a-4c46-86db-46b9d543bdff)

user settings info dump:
```
Stable 264272 (5d73bfa)
Host 0.0.42 x64
Linux 64-Bit (6.7.1-Artix1-1)
```

**Comment by programmer2514** [comment] 2024-02-07 20:27
Duplicate of #116

**Closed by programmer2514** 2024-02-07 20:27 UTC
